### ISSUE TITLE
Basic Examples

### ISSUE THREAD

**Issue by arnavprasad** [alexanderkell/elecsim#23]
I get a none-type error when I use the simple world = World(...) initialization. Are there any examples I can access via a notebook?

**Comment by arnavprasad** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-173-472c5b81354a> in <module>
      1 from elecsim.model.world import World
      2 
----> 3 World(initialization_year = 2020, log_level="warning")

~/anaconda3/lib/python3.7/site-packages/elecsim/model/world.py in __init__(self, initialization_year, scenario_file, fitting_params, long_term_fitting_params, future_price_uncertainty_m, future_price_uncertainty_c, carbon_price_scenario, demand_change, demand_distribution, number_of_steps, total_demand, number_of_agents, market_time_splices, data_folder, time_run, nuclear_subsidy, highest_demand, log_level, client_rl, distribution_name, dropbox, gencos_rl, write_data_to_file, rl_port_number)
    131             # self.client = PolicyClient("http://rllibserver:9900")
    132             self.client = client_rl
--> 133             self.eid = self.client.start_episode(training_enabled=True)
    134             self.intial_obs = LatestMarketData(self).get_RL_investment_observations()
    135             # logger.info("self.intial_obs: {}".format(self.intial_obs))

AttributeError: 'NoneType' object has no attribute 'start_episode'

**Comment by alexanderkell** [comment]
Thanks for raising this issue. The issue should now be fixed with the latest commits. Try running with the latest version of elecsim from the repo.
