### ISSUE TITLE
Cloning Issue 

### ISSUE THREAD

**Issue by BLandicho** [alexanderkell/elecsim#78]
Good day! 

I am an undergraduate student looking to pursue the use your software to simulate market operations for a specific scenario. In the process of following the instructions linked I've come across multiple errors and one with regards to cloning the repository, which seems to cause the other problems in using the program such as installation of the requirements.txt file. I was wondering if it is an error on my part as I am not too familiar with using github, or if there is a way I could work around it. Attached below is the error which occurs upon cloning the repository
[ElecSim Error.docx](https://github.com/alexanderkell/elecsim/files/9692301/ElecSim.Error.docx)
Thank you so much!

**Comment by energy-trader** [comment]
I've experienced the same error, were you able to solve this?

**Comment by alexanderkell** [comment]
Apologies for the delayed response. I am no longer maintaining this, but I've deleted the data files in question. So hopefully should now work.

**Comment by energy-trader** [comment]
Thanks so much download works perfect! I understand you're not maintaining the repository, however would it be possible to email/linkedin message you about your thesis at all? I am current 4th yr meng student at durham 
Completely understand if your busy thanks again!

**Comment by alexanderkell** [comment]
sure! Feel free to connect on LinkedIn
